### ISSUE TITLE
No way to check if there is a crate in front while standing on crates.

### ISSUE THREAD

**Issue by Firestar99** [kypello/RobotCoding#1]
My solution to the last level, software developer style:
![image](https://user-images.githubusercontent.com/31222740/185928733-3034b1a1-5d52-40e7-8bfc-db556b7db922.png)

This program fails after the robot places the 7th box which is the first box in the 3rd row of the bridge. The robot is in line 2 where it should move forward until you find a crate and then pick it up. But `checkInFront()` doesn't just check in front, but also checks "in front and one below" finding the box of the 1st row of the bridge, exiting the while loop to try and fail to pickup said box. 

This however means that one cannot check with certainty if there is a box in front of the robot, because there may just be a box in front and below the robot it will recognize instead, which also cannot be picked up.

**Comment by kypello** [comment]
This is fixed in the most recent commit. Checking in front for a crate now only checks directly in front, and ignores crates in the floor
